#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "packets.pb.h"  // generated by protobuf_generate_cpp() from proto/packets.proto

namespace unboundmp::protocol {

// Wire format: [uint32 big-endian length][serialized Envelope bytes]
// length is capped at kMaxFrameBytes (see constants.h).

// Serializes `envelope` into `out_bytes`, appending the 4-byte length
// prefix followed by the protobuf-encoded payload. Returns false if the
// message fails to serialize or exceeds kMaxFrameBytes.
bool EncodeFrame(const Envelope& envelope, std::vector<uint8_t>& out_bytes);

// Incrementally reassembles frames out of a byte stream (e.g. bytes read
// off a TCP socket, which may arrive split or coalesced across multiple
// reads). Feed raw bytes in with Feed(); pull complete, decoded Envelopes
// out with TryExtractNext(). Not thread-safe; one instance per connection.
class FrameDecoder {
 public:
  // Appends newly-received bytes to the internal buffer.
  void Feed(const uint8_t* data, size_t len);

  // If a complete frame is available, decodes it into an Envelope and
  // consumes it from the internal buffer. Returns std::nullopt if more
  // bytes are needed, or if the buffered frame fails to parse / exceeds
  // kMaxFrameBytes (in which case the connection should be dropped by the
  // caller — a malformed length prefix means the stream is desynced and
  // cannot be recovered).
  std::optional<Envelope> TryExtractNext();

  // True once TryExtractNext() has returned std::nullopt due to a
  // corrupt/oversized frame rather than "just need more bytes". Callers
  // should check this after every std::nullopt return during the
  // read-more-and-retry loop.
  bool IsCorrupted() const { return corrupted_; }

 private:
  std::vector<uint8_t> buffer_;
  bool corrupted_ = false;
};

}  // namespace unboundmp::protocol
