// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: packets.proto

// Wire protocol for the Pokemon Unbound multiplayer wrapper.
//
// Design notes:
//  - The ROM is never read as "game logic" by the server. The server is a
//    dumb relay + session/auth/position authority. It never parses Pokemon
//    data, move data, or map data.
//  - Trades and battles are modeled as a generic "link session" byte relay.
//    Real GBA trades/battles run over the link cable serial protocol, which
//    mGBA already emulates faithfully. Two clients open a link session
//    through the server, and the server forwards opaque bytes between them
//    exactly as a physical link cable would. Neither the server nor this
//    schema needs to understand Unbound's internal Pokemon/move structures.
//    This also means the protocol does not need to change if Unbound is
//    patched to a new version, since we never touch its memory layout here.
//
// Package/version note: this file is the source of truth. Generated code
// (protoc-gen-cpp / protoc-gen-go) is produced at build time, not committed.
// See /proto/README.md and the top-level Makefile.

// Note: the package is "unboundmp.protocol" (not e.g. "unboundmp.v1") so
// that generated C++ code lands in namespace unboundmp::protocol, matching
// the hand-written serialization.h / packet_dispatcher.h in
// cpp/include/protocol/ without qualification games. Protocol *wire*
// versioning is tracked by Envelope.protocol_version, not by this package
// name — see the Versioning section in proto/README.md.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthResult int32

const (
	AuthResult_AUTH_RESULT_UNSPECIFIED    AuthResult = 0
	AuthResult_AUTH_RESULT_OK             AuthResult = 1
	AuthResult_AUTH_RESULT_USERNAME_TAKEN AuthResult = 2
	AuthResult_AUTH_RESULT_INVALID_NAME   AuthResult = 3
	AuthResult_AUTH_RESULT_SERVER_FULL    AuthResult = 4
)

// Enum value maps for AuthResult.
var (
	AuthResult_name = map[int32]string{
		0: "AUTH_RESULT_UNSPECIFIED",
		1: "AUTH_RESULT_OK",
		2: "AUTH_RESULT_USERNAME_TAKEN",
		3: "AUTH_RESULT_INVALID_NAME",
		4: "AUTH_RESULT_SERVER_FULL",
	}
	AuthResult_value = map[string]int32{
		"AUTH_RESULT_UNSPECIFIED":    0,
		"AUTH_RESULT_OK":             1,
		"AUTH_RESULT_USERNAME_TAKEN": 2,
		"AUTH_RESULT_INVALID_NAME":   3,
		"AUTH_RESULT_SERVER_FULL":    4,
	}
)

func (x AuthResult) Enum() *AuthResult {
	p := new(AuthResult)
	*p = x
	return p
}

func (x AuthResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthResult) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (AuthResult) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x AuthResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthResult.Descriptor instead.
func (AuthResult) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type DisconnectReason int32

const (
	DisconnectReason_DISCONNECT_REASON_UNSPECIFIED     DisconnectReason = 0
	DisconnectReason_DISCONNECT_REASON_CLIENT_QUIT     DisconnectReason = 1
	DisconnectReason_DISCONNECT_REASON_TIMEOUT         DisconnectReason = 2
	DisconnectReason_DISCONNECT_REASON_KICKED          DisconnectReason = 3
	DisconnectReason_DISCONNECT_REASON_SERVER_SHUTDOWN DisconnectReason = 4
	DisconnectReason_DISCONNECT_REASON_PROTOCOL_ERROR  DisconnectReason = 5
)

// Enum value maps for DisconnectReason.
var (
	DisconnectReason_name = map[int32]string{
		0: "DISCONNECT_REASON_UNSPECIFIED",
		1: "DISCONNECT_REASON_CLIENT_QUIT",
		2: "DISCONNECT_REASON_TIMEOUT",
		3: "DISCONNECT_REASON_KICKED",
		4: "DISCONNECT_REASON_SERVER_SHUTDOWN",
		5: "DISCONNECT_REASON_PROTOCOL_ERROR",
	}
	DisconnectReason_value = map[string]int32{
		"DISCONNECT_REASON_UNSPECIFIED":     0,
		"DISCONNECT_REASON_CLIENT_QUIT":     1,
		"DISCONNECT_REASON_TIMEOUT":         2,
		"DISCONNECT_REASON_KICKED":          3,
		"DISCONNECT_REASON_SERVER_SHUTDOWN": 4,
		"DISCONNECT_REASON_PROTOCOL_ERROR":  5,
	}
)

func (x DisconnectReason) Enum() *DisconnectReason {
	p := new(DisconnectReason)
	*p = x
	return p
}

func (x DisconnectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[1].Descriptor()
}

func (DisconnectReason) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[1]
}

func (x DisconnectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectReason.Descriptor instead.
func (DisconnectReason) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_DOWN        Direction = 1
	Direction_DIRECTION_UP          Direction = 2
	Direction_DIRECTION_LEFT        Direction = 3
	Direction_DIRECTION_RIGHT       Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_DOWN",
		2: "DIRECTION_UP",
		3: "DIRECTION_LEFT",
		4: "DIRECTION_RIGHT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_DOWN":        1,
		"DIRECTION_UP":          2,
		"DIRECTION_LEFT":        3,
		"DIRECTION_RIGHT":       4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

type MovementMode int32

const (
	MovementMode_MOVEMENT_MODE_UNSPECIFIED MovementMode = 0
	MovementMode_MOVEMENT_MODE_WALK        MovementMode = 1
	MovementMode_MOVEMENT_MODE_RUN         MovementMode = 2
	MovementMode_MOVEMENT_MODE_BIKE        MovementMode = 3
	MovementMode_MOVEMENT_MODE_SURF        MovementMode = 4
)

// Enum value maps for MovementMode.
var (
	MovementMode_name = map[int32]string{
		0: "MOVEMENT_MODE_UNSPECIFIED",
		1: "MOVEMENT_MODE_WALK",
		2: "MOVEMENT_MODE_RUN",
		3: "MOVEMENT_MODE_BIKE",
		4: "MOVEMENT_MODE_SURF",
	}
	MovementMode_value = map[string]int32{
		"MOVEMENT_MODE_UNSPECIFIED": 0,
		"MOVEMENT_MODE_WALK":        1,
		"MOVEMENT_MODE_RUN":         2,
		"MOVEMENT_MODE_BIKE":        3,
		"MOVEMENT_MODE_SURF":        4,
	}
)

func (x MovementMode) Enum() *MovementMode {
	p := new(MovementMode)
	*p = x
	return p
}

func (x MovementMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovementMode) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[3].Descriptor()
}

func (MovementMode) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[3]
}

func (x MovementMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovementMode.Descriptor instead.
func (MovementMode) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

type LinkMode int32

const (
	LinkMode_LINK_MODE_UNSPECIFIED LinkMode = 0
	LinkMode_LINK_MODE_TRADE       LinkMode = 1
	LinkMode_LINK_MODE_BATTLE      LinkMode = 2
)

// Enum value maps for LinkMode.
var (
	LinkMode_name = map[int32]string{
		0: "LINK_MODE_UNSPECIFIED",
		1: "LINK_MODE_TRADE",
		2: "LINK_MODE_BATTLE",
	}
	LinkMode_value = map[string]int32{
		"LINK_MODE_UNSPECIFIED": 0,
		"LINK_MODE_TRADE":       1,
		"LINK_MODE_BATTLE":      2,
	}
)

func (x LinkMode) Enum() *LinkMode {
	p := new(LinkMode)
	*p = x
	return p
}

func (x LinkMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkMode) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[4].Descriptor()
}

func (LinkMode) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[4]
}

func (x LinkMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkMode.Descriptor instead.
func (LinkMode) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

type LinkSessionEndReason int32

const (
	LinkSessionEndReason_LINK_SESSION_END_REASON_UNSPECIFIED LinkSessionEndReason = 0
	LinkSessionEndReason_LINK_SESSION_END_REASON_COMPLETED   LinkSessionEndReason = 1
	LinkSessionEndReason_LINK_SESSION_END_REASON_CANCELLED   LinkSessionEndReason = 2
	LinkSessionEndReason_LINK_SESSION_END_REASON_PEER_LEFT   LinkSessionEndReason = 3
	LinkSessionEndReason_LINK_SESSION_END_REASON_TIMEOUT     LinkSessionEndReason = 4
)

// Enum value maps for LinkSessionEndReason.
var (
	LinkSessionEndReason_name = map[int32]string{
		0: "LINK_SESSION_END_REASON_UNSPECIFIED",
		1: "LINK_SESSION_END_REASON_COMPLETED",
		2: "LINK_SESSION_END_REASON_CANCELLED",
		3: "LINK_SESSION_END_REASON_PEER_LEFT",
		4: "LINK_SESSION_END_REASON_TIMEOUT",
	}
	LinkSessionEndReason_value = map[string]int32{
		"LINK_SESSION_END_REASON_UNSPECIFIED": 0,
		"LINK_SESSION_END_REASON_COMPLETED":   1,
		"LINK_SESSION_END_REASON_CANCELLED":   2,
		"LINK_SESSION_END_REASON_PEER_LEFT":   3,
		"LINK_SESSION_END_REASON_TIMEOUT":     4,
	}
)

func (x LinkSessionEndReason) Enum() *LinkSessionEndReason {
	p := new(LinkSessionEndReason)
	*p = x
	return p
}

func (x LinkSessionEndReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkSessionEndReason) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[5].Descriptor()
}

func (LinkSessionEndReason) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[5]
}

func (x LinkSessionEndReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkSessionEndReason.Descriptor instead.
func (LinkSessionEndReason) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED      ErrorCode = 0
	ErrorCode_ERROR_CODE_MALFORMED_PACKET ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHENTICATED  ErrorCode = 2
	ErrorCode_ERROR_CODE_UNKNOWN_PLAYER   ErrorCode = 3
	ErrorCode_ERROR_CODE_UNKNOWN_SESSION  ErrorCode = 4
	ErrorCode_ERROR_CODE_VERSION_MISMATCH ErrorCode = 5
	ErrorCode_ERROR_CODE_RATE_LIMITED     ErrorCode = 6
	ErrorCode_ERROR_CODE_INTERNAL         ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_MALFORMED_PACKET",
		2: "ERROR_CODE_UNAUTHENTICATED",
		3: "ERROR_CODE_UNKNOWN_PLAYER",
		4: "ERROR_CODE_UNKNOWN_SESSION",
		5: "ERROR_CODE_VERSION_MISMATCH",
		6: "ERROR_CODE_RATE_LIMITED",
		7: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":      0,
		"ERROR_CODE_MALFORMED_PACKET": 1,
		"ERROR_CODE_UNAUTHENTICATED":  2,
		"ERROR_CODE_UNKNOWN_PLAYER":   3,
		"ERROR_CODE_UNKNOWN_SESSION":  4,
		"ERROR_CODE_VERSION_MISMATCH": 5,
		"ERROR_CODE_RATE_LIMITED":     6,
		"ERROR_CODE_INTERNAL":         7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[6].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[6]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

// Every message on the wire is an Envelope. This gives every packet a
// protocol version, a monotonic sequence number (per-connection), and a
// send timestamp, independent of payload type. See constants.proto-equivalent
// values in constants.h / config/constants.go for PROTOCOL_VERSION.
type Envelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Sequence        uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampMs     int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_ClientHello
	//	*Envelope_ServerHello
	//	*Envelope_AuthRequest
	//	*Envelope_AuthResponse
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Disconnect
	//	*Envelope_PlayerJoined
	//	*Envelope_PlayerLeft
	//	*Envelope_WorldSnapshot
	//	*Envelope_PlayerStateUpdate
	//	*Envelope_FollowerUpdate
	//	*Envelope_LinkSessionRequest
	//	*Envelope_LinkSessionResponse
	//	*Envelope_LinkSessionData
	//	*Envelope_LinkSessionEnd
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *Envelope) GetServerHello() *ServerHello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ServerHello); ok {
			return x.ServerHello
		}
	}
	return nil
}

func (x *Envelope) GetAuthRequest() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *Envelope) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetDisconnect() *Disconnect {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *Envelope) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *Envelope) GetPlayerLeft() *PlayerLeft {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PlayerLeft); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *Envelope) GetWorldSnapshot() *WorldSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WorldSnapshot); ok {
			return x.WorldSnapshot
		}
	}
	return nil
}

func (x *Envelope) GetPlayerStateUpdate() *PlayerStateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PlayerStateUpdate); ok {
			return x.PlayerStateUpdate
		}
	}
	return nil
}

func (x *Envelope) GetFollowerUpdate() *FollowerUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FollowerUpdate); ok {
			return x.FollowerUpdate
		}
	}
	return nil
}

func (x *Envelope) GetLinkSessionRequest() *LinkSessionRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LinkSessionRequest); ok {
			return x.LinkSessionRequest
		}
	}
	return nil
}

func (x *Envelope) GetLinkSessionResponse() *LinkSessionResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LinkSessionResponse); ok {
			return x.LinkSessionResponse
		}
	}
	return nil
}

func (x *Envelope) GetLinkSessionData() *LinkSessionData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LinkSessionData); ok {
			return x.LinkSessionData
		}
	}
	return nil
}

func (x *Envelope) GetLinkSessionEnd() *LinkSessionEnd {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LinkSessionEnd); ok {
			return x.LinkSessionEnd
		}
	}
	return nil
}

func (x *Envelope) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_ClientHello struct {
	// Handshake
	ClientHello *ClientHello `protobuf:"bytes,10,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type Envelope_ServerHello struct {
	ServerHello *ServerHello `protobuf:"bytes,11,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type Envelope_AuthRequest struct {
	// Auth
	AuthRequest *AuthRequest `protobuf:"bytes,12,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type Envelope_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,13,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type Envelope_Ping struct {
	// Liveness
	Ping *Ping `protobuf:"bytes,14,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,15,opt,name=pong,proto3,oneof"`
}

type Envelope_Disconnect struct {
	// Session lifecycle
	Disconnect *Disconnect `protobuf:"bytes,16,opt,name=disconnect,proto3,oneof"`
}

type Envelope_PlayerJoined struct {
	// World / presence
	PlayerJoined *PlayerJoined `protobuf:"bytes,20,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type Envelope_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,21,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

type Envelope_WorldSnapshot struct {
	WorldSnapshot *WorldSnapshot `protobuf:"bytes,22,opt,name=world_snapshot,json=worldSnapshot,proto3,oneof"`
}

type Envelope_PlayerStateUpdate struct {
	PlayerStateUpdate *PlayerStateUpdate `protobuf:"bytes,23,opt,name=player_state_update,json=playerStateUpdate,proto3,oneof"`
}

type Envelope_FollowerUpdate struct {
	// Follower Pokemon (first party slot)
	FollowerUpdate *FollowerUpdate `protobuf:"bytes,30,opt,name=follower_update,json=followerUpdate,proto3,oneof"`
}

type Envelope_LinkSessionRequest struct {
	// Link session (covers both trade and battle - see notes above)
	LinkSessionRequest *LinkSessionRequest `protobuf:"bytes,40,opt,name=link_session_request,json=linkSessionRequest,proto3,oneof"`
}

type Envelope_LinkSessionResponse struct {
	LinkSessionResponse *LinkSessionResponse `protobuf:"bytes,41,opt,name=link_session_response,json=linkSessionResponse,proto3,oneof"`
}

type Envelope_LinkSessionData struct {
	LinkSessionData *LinkSessionData `protobuf:"bytes,42,opt,name=link_session_data,json=linkSessionData,proto3,oneof"`
}

type Envelope_LinkSessionEnd struct {
	LinkSessionEnd *LinkSessionEnd `protobuf:"bytes,43,opt,name=link_session_end,json=linkSessionEnd,proto3,oneof"`
}

type Envelope_Error struct {
	// Errors
	Error *ErrorMessage `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*Envelope_ClientHello) isEnvelope_Payload() {}

func (*Envelope_ServerHello) isEnvelope_Payload() {}

func (*Envelope_AuthRequest) isEnvelope_Payload() {}

func (*Envelope_AuthResponse) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_Disconnect) isEnvelope_Payload() {}

func (*Envelope_PlayerJoined) isEnvelope_Payload() {}

func (*Envelope_PlayerLeft) isEnvelope_Payload() {}

func (*Envelope_WorldSnapshot) isEnvelope_Payload() {}

func (*Envelope_PlayerStateUpdate) isEnvelope_Payload() {}

func (*Envelope_FollowerUpdate) isEnvelope_Payload() {}

func (*Envelope_LinkSessionRequest) isEnvelope_Payload() {}

func (*Envelope_LinkSessionResponse) isEnvelope_Payload() {}

func (*Envelope_LinkSessionData) isEnvelope_Payload() {}

func (*Envelope_LinkSessionEnd) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

// First message sent by the client immediately after connecting, before
// authentication. Lets the server reject incompatible clients cleanly.
type ClientHello struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientProtocolVersion uint32                 `protobuf:"varint,1,opt,name=client_protocol_version,json=clientProtocolVersion,proto3" json:"client_protocol_version,omitempty"`
	ClientVersionString   string                 `protobuf:"bytes,2,opt,name=client_version_string,json=clientVersionString,proto3" json:"client_version_string,omitempty"` // human-readable, e.g. "0.1.0"
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetClientProtocolVersion() uint32 {
	if x != nil {
		return x.ClientProtocolVersion
	}
	return 0
}

func (x *ClientHello) GetClientVersionString() string {
	if x != nil {
		return x.ClientVersionString
	}
	return ""
}

// Server's reply to ClientHello. `accepted = false` means the server will
// close the connection after sending this (e.g. version mismatch).
type ServerHello struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Accepted              bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ServerProtocolVersion uint32                 `protobuf:"varint,2,opt,name=server_protocol_version,json=serverProtocolVersion,proto3" json:"server_protocol_version,omitempty"`
	ServerVersionString   string                 `protobuf:"bytes,3,opt,name=server_version_string,json=serverVersionString,proto3" json:"server_version_string,omitempty"`
	RejectReason          string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // set only when accepted = false
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *ServerHello) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ServerHello) GetServerProtocolVersion() uint32 {
	if x != nil {
		return x.ServerProtocolVersion
	}
	return 0
}

func (x *ServerHello) GetServerVersionString() string {
	if x != nil {
		return x.ServerVersionString
	}
	return ""
}

func (x *ServerHello) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// Simple username-based auth. No password/token in this milestone.
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AuthResult             `protobuf:"varint,1,opt,name=result,proto3,enum=unboundmp.protocol.AuthResult" json:"result,omitempty"`
	PlayerId      uint32                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // valid only when result == AUTH_RESULT_OK
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                    // optional human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetResult() AuthResult {
	if x != nil {
		return x.Result
	}
	return AuthResult_AUTH_RESULT_UNSPECIFIED
}

func (x *AuthResponse) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        DisconnectReason       `protobuf:"varint,1,opt,name=reason,proto3,enum=unboundmp.protocol.DisconnectReason" json:"reason,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *Disconnect) GetReason() DisconnectReason {
	if x != nil {
		return x.Reason
	}
	return DisconnectReason_DISCONNECT_REASON_UNSPECIFIED
}

func (x *Disconnect) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// map_bank/map_number mirror the Pokemon-engine convention of identifying
// a map by (bank, number) rather than a single global id, since that's how
// Unbound (and vanilla FireRed/Emerald-derived engines) address maps.
type PlayerStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapBank       uint32                 `protobuf:"varint,2,opt,name=map_bank,json=mapBank,proto3" json:"map_bank,omitempty"`
	MapNumber     uint32                 `protobuf:"varint,3,opt,name=map_number,json=mapNumber,proto3" json:"map_number,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	Facing        Direction              `protobuf:"varint,6,opt,name=facing,proto3,enum=unboundmp.protocol.Direction" json:"facing,omitempty"`
	Movement      MovementMode           `protobuf:"varint,7,opt,name=movement,proto3,enum=unboundmp.protocol.MovementMode" json:"movement,omitempty"`
	IsMoving      bool                   `protobuf:"varint,8,opt,name=is_moving,json=isMoving,proto3" json:"is_moving,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStateUpdate) Reset() {
	*x = PlayerStateUpdate{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStateUpdate) ProtoMessage() {}

func (x *PlayerStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStateUpdate.ProtoReflect.Descriptor instead.
func (*PlayerStateUpdate) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerStateUpdate) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerStateUpdate) GetMapBank() uint32 {
	if x != nil {
		return x.MapBank
	}
	return 0
}

func (x *PlayerStateUpdate) GetMapNumber() uint32 {
	if x != nil {
		return x.MapNumber
	}
	return 0
}

func (x *PlayerStateUpdate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerStateUpdate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerStateUpdate) GetFacing() Direction {
	if x != nil {
		return x.Facing
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *PlayerStateUpdate) GetMovement() MovementMode {
	if x != nil {
		return x.Movement
	}
	return MovementMode_MOVEMENT_MODE_UNSPECIFIED
}

func (x *PlayerStateUpdate) GetIsMoving() bool {
	if x != nil {
		return x.IsMoving
	}
	return false
}

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	State         *PlayerStateUpdate     `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Follower      *FollowerUpdate        `protobuf:"bytes,4,opt,name=follower,proto3" json:"follower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerInfo) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerInfo) GetState() *PlayerStateUpdate {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *PlayerInfo) GetFollower() *FollowerUpdate {
	if x != nil {
		return x.Follower
	}
	return nil
}

// Sent once, right after a player finishes joining, to every other player
// already on the same map/session.
type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerInfo            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerJoined) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        DisconnectReason       `protobuf:"varint,2,opt,name=reason,proto3,enum=unboundmp.protocol.DisconnectReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerLeft) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerLeft) GetReason() DisconnectReason {
	if x != nil {
		return x.Reason
	}
	return DisconnectReason_DISCONNECT_REASON_UNSPECIFIED
}

// Full state resync, sent on join and periodically as a keyframe so
// clients can recover from any dropped delta updates.
type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerInfo          `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

func (x *WorldSnapshot) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type FollowerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SpeciesId     uint32                 `protobuf:"varint,2,opt,name=species_id,json=speciesId,proto3" json:"species_id,omitempty"` // 0 = no follower / follower hidden
	Visible       bool                   `protobuf:"varint,3,opt,name=visible,proto3" json:"visible,omitempty"`
	Shiny         bool                   `protobuf:"varint,4,opt,name=shiny,proto3" json:"shiny,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerUpdate) Reset() {
	*x = FollowerUpdate{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerUpdate) ProtoMessage() {}

func (x *FollowerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerUpdate.ProtoReflect.Descriptor instead.
func (*FollowerUpdate) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *FollowerUpdate) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FollowerUpdate) GetSpeciesId() uint32 {
	if x != nil {
		return x.SpeciesId
	}
	return 0
}

func (x *FollowerUpdate) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *FollowerUpdate) GetShiny() bool {
	if x != nil {
		return x.Shiny
	}
	return false
}

// Player A asks the server to open a link session with player B. The server
// only validates that both players exist, are idle, and are on adjacent/
// valid tiles per game rules enforced client-side; it does not validate
// game state.
type LinkSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetPlayerId uint32                 `protobuf:"varint,1,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	Mode           LinkMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=unboundmp.protocol.LinkMode" json:"mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LinkSessionRequest) Reset() {
	*x = LinkSessionRequest{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkSessionRequest) ProtoMessage() {}

func (x *LinkSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkSessionRequest.ProtoReflect.Descriptor instead.
func (*LinkSessionRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *LinkSessionRequest) GetTargetPlayerId() uint32 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

func (x *LinkSessionRequest) GetMode() LinkMode {
	if x != nil {
		return x.Mode
	}
	return LinkMode_LINK_MODE_UNSPECIFIED
}

type LinkSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 0 if rejected
	InitiatorPlayerId uint32                 `protobuf:"varint,2,opt,name=initiator_player_id,json=initiatorPlayerId,proto3" json:"initiator_player_id,omitempty"`
	TargetPlayerId    uint32                 `protobuf:"varint,3,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	Mode              LinkMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=unboundmp.protocol.LinkMode" json:"mode,omitempty"`
	Accepted          bool                   `protobuf:"varint,5,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason      string                 `protobuf:"bytes,6,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LinkSessionResponse) Reset() {
	*x = LinkSessionResponse{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkSessionResponse) ProtoMessage() {}

func (x *LinkSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkSessionResponse.ProtoReflect.Descriptor instead.
func (*LinkSessionResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *LinkSessionResponse) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *LinkSessionResponse) GetInitiatorPlayerId() uint32 {
	if x != nil {
		return x.InitiatorPlayerId
	}
	return 0
}

func (x *LinkSessionResponse) GetTargetPlayerId() uint32 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

func (x *LinkSessionResponse) GetMode() LinkMode {
	if x != nil {
		return x.Mode
	}
	return LinkMode_LINK_MODE_UNSPECIFIED
}

func (x *LinkSessionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *LinkSessionResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// Opaque relay of link-cable-equivalent bytes between the two participants
// of a session. The server forwards this payload verbatim to the other
// session participant and never inspects its contents.
type LinkSessionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromPlayerId  uint32                 `protobuf:"varint,2,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	StreamSeq     uint64                 `protobuf:"varint,4,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"` // per-session monotonic counter, for gap detection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkSessionData) Reset() {
	*x = LinkSessionData{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkSessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkSessionData) ProtoMessage() {}

func (x *LinkSessionData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkSessionData.ProtoReflect.Descriptor instead.
func (*LinkSessionData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

func (x *LinkSessionData) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *LinkSessionData) GetFromPlayerId() uint32 {
	if x != nil {
		return x.FromPlayerId
	}
	return 0
}

func (x *LinkSessionData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LinkSessionData) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

type LinkSessionEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        LinkSessionEndReason   `protobuf:"varint,2,opt,name=reason,proto3,enum=unboundmp.protocol.LinkSessionEndReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkSessionEnd) Reset() {
	*x = LinkSessionEnd{}
	mi := &file_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkSessionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkSessionEnd) ProtoMessage() {}

func (x *LinkSessionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkSessionEnd.ProtoReflect.Descriptor instead.
func (*LinkSessionEnd) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{17}
}

func (x *LinkSessionEnd) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *LinkSessionEnd) GetReason() LinkSessionEndReason {
	if x != nil {
		return x.Reason
	}
	return LinkSessionEndReason_LINK_SESSION_END_REASON_UNSPECIFIED
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=unboundmp.protocol.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorMessage) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\x12unboundmp.protocol\"\xd4\n" +
	"\n" +
	"\bEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12D\n" +
	"\fclient_hello\x18\n" +
	" \x01(\v2\x1f.unboundmp.protocol.ClientHelloH\x00R\vclientHello\x12D\n" +
	"\fserver_hello\x18\v \x01(\v2\x1f.unboundmp.protocol.ServerHelloH\x00R\vserverHello\x12D\n" +
	"\fauth_request\x18\f \x01(\v2\x1f.unboundmp.protocol.AuthRequestH\x00R\vauthRequest\x12G\n" +
	"\rauth_response\x18\r \x01(\v2 .unboundmp.protocol.AuthResponseH\x00R\fauthResponse\x12.\n" +
	"\x04ping\x18\x0e \x01(\v2\x18.unboundmp.protocol.PingH\x00R\x04ping\x12.\n" +
	"\x04pong\x18\x0f \x01(\v2\x18.unboundmp.protocol.PongH\x00R\x04pong\x12@\n" +
	"\n" +
	"disconnect\x18\x10 \x01(\v2\x1e.unboundmp.protocol.DisconnectH\x00R\n" +
	"disconnect\x12G\n" +
	"\rplayer_joined\x18\x14 \x01(\v2 .unboundmp.protocol.PlayerJoinedH\x00R\fplayerJoined\x12A\n" +
	"\vplayer_left\x18\x15 \x01(\v2\x1e.unboundmp.protocol.PlayerLeftH\x00R\n" +
	"playerLeft\x12J\n" +
	"\x0eworld_snapshot\x18\x16 \x01(\v2!.unboundmp.protocol.WorldSnapshotH\x00R\rworldSnapshot\x12W\n" +
	"\x13player_state_update\x18\x17 \x01(\v2%.unboundmp.protocol.PlayerStateUpdateH\x00R\x11playerStateUpdate\x12M\n" +
	"\x0ffollower_update\x18\x1e \x01(\v2\".unboundmp.protocol.FollowerUpdateH\x00R\x0efollowerUpdate\x12Z\n" +
	"\x14link_session_request\x18( \x01(\v2&.unboundmp.protocol.LinkSessionRequestH\x00R\x12linkSessionRequest\x12]\n" +
	"\x15link_session_response\x18) \x01(\v2'.unboundmp.protocol.LinkSessionResponseH\x00R\x13linkSessionResponse\x12Q\n" +
	"\x11link_session_data\x18* \x01(\v2#.unboundmp.protocol.LinkSessionDataH\x00R\x0flinkSessionData\x12N\n" +
	"\x10link_session_end\x18+ \x01(\v2\".unboundmp.protocol.LinkSessionEndH\x00R\x0elinkSessionEnd\x128\n" +
	"\x05error\x18c \x01(\v2 .unboundmp.protocol.ErrorMessageH\x00R\x05errorB\t\n" +
	"\apayload\"y\n" +
	"\vClientHello\x126\n" +
	"\x17client_protocol_version\x18\x01 \x01(\rR\x15clientProtocolVersion\x122\n" +
	"\x15client_version_string\x18\x02 \x01(\tR\x13clientVersionString\"\xba\x01\n" +
	"\vServerHello\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x126\n" +
	"\x17server_protocol_version\x18\x02 \x01(\rR\x15serverProtocolVersion\x122\n" +
	"\x15server_version_string\x18\x03 \x01(\tR\x13serverVersionString\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\")\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"}\n" +
	"\fAuthResponse\x126\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1e.unboundmp.protocol.AuthResultR\x06result\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\rR\bplayerId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"b\n" +
	"\n" +
	"Disconnect\x12<\n" +
	"\x06reason\x18\x01 \x01(\x0e2$.unboundmp.protocol.DisconnectReasonR\x06reason\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x98\x02\n" +
	"\x11PlayerStateUpdate\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12\x19\n" +
	"\bmap_bank\x18\x02 \x01(\rR\amapBank\x12\x1d\n" +
	"\n" +
	"map_number\x18\x03 \x01(\rR\tmapNumber\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\x125\n" +
	"\x06facing\x18\x06 \x01(\x0e2\x1d.unboundmp.protocol.DirectionR\x06facing\x12<\n" +
	"\bmovement\x18\a \x01(\x0e2 .unboundmp.protocol.MovementModeR\bmovement\x12\x1b\n" +
	"\tis_moving\x18\b \x01(\bR\bisMoving\"\xc2\x01\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12;\n" +
	"\x05state\x18\x03 \x01(\v2%.unboundmp.protocol.PlayerStateUpdateR\x05state\x12>\n" +
	"\bfollower\x18\x04 \x01(\v2\".unboundmp.protocol.FollowerUpdateR\bfollower\"F\n" +
	"\fPlayerJoined\x126\n" +
	"\x06player\x18\x01 \x01(\v2\x1e.unboundmp.protocol.PlayerInfoR\x06player\"g\n" +
	"\n" +
	"PlayerLeft\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12<\n" +
	"\x06reason\x18\x02 \x01(\x0e2$.unboundmp.protocol.DisconnectReasonR\x06reason\"I\n" +
	"\rWorldSnapshot\x128\n" +
	"\aplayers\x18\x01 \x03(\v2\x1e.unboundmp.protocol.PlayerInfoR\aplayers\"|\n" +
	"\x0eFollowerUpdate\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12\x1d\n" +
	"\n" +
	"species_id\x18\x02 \x01(\rR\tspeciesId\x12\x18\n" +
	"\avisible\x18\x03 \x01(\bR\avisible\x12\x14\n" +
	"\x05shiny\x18\x04 \x01(\bR\x05shiny\"p\n" +
	"\x12LinkSessionRequest\x12(\n" +
	"\x10target_player_id\x18\x01 \x01(\rR\x0etargetPlayerId\x120\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1c.unboundmp.protocol.LinkModeR\x04mode\"\x81\x02\n" +
	"\x13LinkSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12.\n" +
	"\x13initiator_player_id\x18\x02 \x01(\rR\x11initiatorPlayerId\x12(\n" +
	"\x10target_player_id\x18\x03 \x01(\rR\x0etargetPlayerId\x120\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1c.unboundmp.protocol.LinkModeR\x04mode\x12\x1a\n" +
	"\baccepted\x18\x05 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x06 \x01(\tR\frejectReason\"\x8f\x01\n" +
	"\x0fLinkSessionData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12$\n" +
	"\x0efrom_player_id\x18\x02 \x01(\rR\ffromPlayerId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x04 \x01(\x04R\tstreamSeq\"q\n" +
	"\x0eLinkSessionEnd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12@\n" +
	"\x06reason\x18\x02 \x01(\x0e2(.unboundmp.protocol.LinkSessionEndReasonR\x06reason\"[\n" +
	"\fErrorMessage\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.unboundmp.protocol.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x98\x01\n" +
	"\n" +
	"AuthResult\x12\x1b\n" +
	"\x17AUTH_RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eAUTH_RESULT_OK\x10\x01\x12\x1e\n" +
	"\x1aAUTH_RESULT_USERNAME_TAKEN\x10\x02\x12\x1c\n" +
	"\x18AUTH_RESULT_INVALID_NAME\x10\x03\x12\x1b\n" +
	"\x17AUTH_RESULT_SERVER_FULL\x10\x04*\xe2\x01\n" +
	"\x10DisconnectReason\x12!\n" +
	"\x1dDISCONNECT_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDISCONNECT_REASON_CLIENT_QUIT\x10\x01\x12\x1d\n" +
	"\x19DISCONNECT_REASON_TIMEOUT\x10\x02\x12\x1c\n" +
	"\x18DISCONNECT_REASON_KICKED\x10\x03\x12%\n" +
	"!DISCONNECT_REASON_SERVER_SHUTDOWN\x10\x04\x12$\n" +
	" DISCONNECT_REASON_PROTOCOL_ERROR\x10\x05*u\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDIRECTION_DOWN\x10\x01\x12\x10\n" +
	"\fDIRECTION_UP\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_LEFT\x10\x03\x12\x13\n" +
	"\x0fDIRECTION_RIGHT\x10\x04*\x8c\x01\n" +
	"\fMovementMode\x12\x1d\n" +
	"\x19MOVEMENT_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MOVEMENT_MODE_WALK\x10\x01\x12\x15\n" +
	"\x11MOVEMENT_MODE_RUN\x10\x02\x12\x16\n" +
	"\x12MOVEMENT_MODE_BIKE\x10\x03\x12\x16\n" +
	"\x12MOVEMENT_MODE_SURF\x10\x04*P\n" +
	"\bLinkMode\x12\x19\n" +
	"\x15LINK_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLINK_MODE_TRADE\x10\x01\x12\x14\n" +
	"\x10LINK_MODE_BATTLE\x10\x02*\xd9\x01\n" +
	"\x14LinkSessionEndReason\x12'\n" +
	"#LINK_SESSION_END_REASON_UNSPECIFIED\x10\x00\x12%\n" +
	"!LINK_SESSION_END_REASON_COMPLETED\x10\x01\x12%\n" +
	"!LINK_SESSION_END_REASON_CANCELLED\x10\x02\x12%\n" +
	"!LINK_SESSION_END_REASON_PEER_LEFT\x10\x03\x12#\n" +
	"\x1fLINK_SESSION_END_REASON_TIMEOUT\x10\x04*\xfe\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_MALFORMED_PACKET\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_UNKNOWN_PLAYER\x10\x03\x12\x1e\n" +
	"\x1aERROR_CODE_UNKNOWN_SESSION\x10\x04\x12\x1f\n" +
	"\x1bERROR_CODE_VERSION_MISMATCH\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\x06\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\aB+Z)unbound-mp/server/internal/protocol/pb;pbb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_packets_proto_goTypes = []any{
	(AuthResult)(0),             // 0: unboundmp.protocol.AuthResult
	(DisconnectReason)(0),       // 1: unboundmp.protocol.DisconnectReason
	(Direction)(0),              // 2: unboundmp.protocol.Direction
	(MovementMode)(0),           // 3: unboundmp.protocol.MovementMode
	(LinkMode)(0),               // 4: unboundmp.protocol.LinkMode
	(LinkSessionEndReason)(0),   // 5: unboundmp.protocol.LinkSessionEndReason
	(ErrorCode)(0),              // 6: unboundmp.protocol.ErrorCode
	(*Envelope)(nil),            // 7: unboundmp.protocol.Envelope
	(*ClientHello)(nil),         // 8: unboundmp.protocol.ClientHello
	(*ServerHello)(nil),         // 9: unboundmp.protocol.ServerHello
	(*AuthRequest)(nil),         // 10: unboundmp.protocol.AuthRequest
	(*AuthResponse)(nil),        // 11: unboundmp.protocol.AuthResponse
	(*Ping)(nil),                // 12: unboundmp.protocol.Ping
	(*Pong)(nil),                // 13: unboundmp.protocol.Pong
	(*Disconnect)(nil),          // 14: unboundmp.protocol.Disconnect
	(*PlayerStateUpdate)(nil),   // 15: unboundmp.protocol.PlayerStateUpdate
	(*PlayerInfo)(nil),          // 16: unboundmp.protocol.PlayerInfo
	(*PlayerJoined)(nil),        // 17: unboundmp.protocol.PlayerJoined
	(*PlayerLeft)(nil),          // 18: unboundmp.protocol.PlayerLeft
	(*WorldSnapshot)(nil),       // 19: unboundmp.protocol.WorldSnapshot
	(*FollowerUpdate)(nil),      // 20: unboundmp.protocol.FollowerUpdate
	(*LinkSessionRequest)(nil),  // 21: unboundmp.protocol.LinkSessionRequest
	(*LinkSessionResponse)(nil), // 22: unboundmp.protocol.LinkSessionResponse
	(*LinkSessionData)(nil),     // 23: unboundmp.protocol.LinkSessionData
	(*LinkSessionEnd)(nil),      // 24: unboundmp.protocol.LinkSessionEnd
	(*ErrorMessage)(nil),        // 25: unboundmp.protocol.ErrorMessage
}
var file_packets_proto_depIdxs = []int32{
	8,  // 0: unboundmp.protocol.Envelope.client_hello:type_name -> unboundmp.protocol.ClientHello
	9,  // 1: unboundmp.protocol.Envelope.server_hello:type_name -> unboundmp.protocol.ServerHello
	10, // 2: unboundmp.protocol.Envelope.auth_request:type_name -> unboundmp.protocol.AuthRequest
	11, // 3: unboundmp.protocol.Envelope.auth_response:type_name -> unboundmp.protocol.AuthResponse
	12, // 4: unboundmp.protocol.Envelope.ping:type_name -> unboundmp.protocol.Ping
	13, // 5: unboundmp.protocol.Envelope.pong:type_name -> unboundmp.protocol.Pong
	14, // 6: unboundmp.protocol.Envelope.disconnect:type_name -> unboundmp.protocol.Disconnect
	17, // 7: unboundmp.protocol.Envelope.player_joined:type_name -> unboundmp.protocol.PlayerJoined
	18, // 8: unboundmp.protocol.Envelope.player_left:type_name -> unboundmp.protocol.PlayerLeft
	19, // 9: unboundmp.protocol.Envelope.world_snapshot:type_name -> unboundmp.protocol.WorldSnapshot
	15, // 10: unboundmp.protocol.Envelope.player_state_update:type_name -> unboundmp.protocol.PlayerStateUpdate
	20, // 11: unboundmp.protocol.Envelope.follower_update:type_name -> unboundmp.protocol.FollowerUpdate
	21, // 12: unboundmp.protocol.Envelope.link_session_request:type_name -> unboundmp.protocol.LinkSessionRequest
	22, // 13: unboundmp.protocol.Envelope.link_session_response:type_name -> unboundmp.protocol.LinkSessionResponse
	23, // 14: unboundmp.protocol.Envelope.link_session_data:type_name -> unboundmp.protocol.LinkSessionData
	24, // 15: unboundmp.protocol.Envelope.link_session_end:type_name -> unboundmp.protocol.LinkSessionEnd
	25, // 16: unboundmp.protocol.Envelope.error:type_name -> unboundmp.protocol.ErrorMessage
	0,  // 17: unboundmp.protocol.AuthResponse.result:type_name -> unboundmp.protocol.AuthResult
	1,  // 18: unboundmp.protocol.Disconnect.reason:type_name -> unboundmp.protocol.DisconnectReason
	2,  // 19: unboundmp.protocol.PlayerStateUpdate.facing:type_name -> unboundmp.protocol.Direction
	3,  // 20: unboundmp.protocol.PlayerStateUpdate.movement:type_name -> unboundmp.protocol.MovementMode
	15, // 21: unboundmp.protocol.PlayerInfo.state:type_name -> unboundmp.protocol.PlayerStateUpdate
	20, // 22: unboundmp.protocol.PlayerInfo.follower:type_name -> unboundmp.protocol.FollowerUpdate
	16, // 23: unboundmp.protocol.PlayerJoined.player:type_name -> unboundmp.protocol.PlayerInfo
	1,  // 24: unboundmp.protocol.PlayerLeft.reason:type_name -> unboundmp.protocol.DisconnectReason
	16, // 25: unboundmp.protocol.WorldSnapshot.players:type_name -> unboundmp.protocol.PlayerInfo
	4,  // 26: unboundmp.protocol.LinkSessionRequest.mode:type_name -> unboundmp.protocol.LinkMode
	4,  // 27: unboundmp.protocol.LinkSessionResponse.mode:type_name -> unboundmp.protocol.LinkMode
	5,  // 28: unboundmp.protocol.LinkSessionEnd.reason:type_name -> unboundmp.protocol.LinkSessionEndReason
	6,  // 29: unboundmp.protocol.ErrorMessage.code:type_name -> unboundmp.protocol.ErrorCode
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_ClientHello)(nil),
		(*Envelope_ServerHello)(nil),
		(*Envelope_AuthRequest)(nil),
		(*Envelope_AuthResponse)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Disconnect)(nil),
		(*Envelope_PlayerJoined)(nil),
		(*Envelope_PlayerLeft)(nil),
		(*Envelope_WorldSnapshot)(nil),
		(*Envelope_PlayerStateUpdate)(nil),
		(*Envelope_FollowerUpdate)(nil),
		(*Envelope_LinkSessionRequest)(nil),
		(*Envelope_LinkSessionResponse)(nil),
		(*Envelope_LinkSessionData)(nil),
		(*Envelope_LinkSessionEnd)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
